FROM python:3.8

WORKDIR /app
ENV MONGODB_ENDPOINT=value

COPY src /requirements.txt

RUN pip3 install --no-cache-dir -r requirements.txt

COPY src/.

CMD [ "python3" , "-m" , "flask", "run" , "--host=0.0.0.0"]